title: Eviloma Status
buildFuture: true
defaultContentLanguage: uk
languageCode: en
baseURL: https://status.eviloma.org
theme: cstate
preserveTaxonomyNames: true
taxonomies:
  affected: affected
outputs:
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
  home:
    - html
    - json
    - rss
    - svg
  term:
    - html
    - json
    - rss
    - svg
outputFormats:
  svg:
    isPlainText: true
    mediaType: image/svg+xml
enableGitInfo: true
params:
  skipSeconds: false
  useRelativeTime: true
  disableDarkMode: false
  shortDateFormat: 15:04 UTC — Jan 2
  down: "#FF4747"
  systems: []
  dateFormat: January 2, 2006 at 3:04 PM UTC
  brand: "#a029e8"
  enableLastMod: true
  headerTextColor: white
  logo: /img/eviloma.png
  incidentPostsPerPage: 10
  googleAnalytics: UA-00000000-1
  alwaysKeepBrandColor: true
  disableComplexCalculations: false
  useLogo: false
  disrupted: "#FFB800"
  notice: "#6EA6FF"
  incidentHistoryFormat: none
  disableIncidentHistory: false
  ok: "#00D68F"
  categories: []
  description: Eviloma services status
  enableCustomHTML: false
  useLargeHeaderDesign: false
