title: Eviloma Status
buildFuture: true
defaultContentLanguage: uk
languageCode: en
baseURL: https://status.eviloma.org
theme: cstate
preserveTaxonomyNames: true
taxonomies:
  affected: affected
outputs:
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
  home:
    - html
    - json
    - rss
    - svg
  term:
    - html
    - json
    - rss
    - svg
outputFormats:
  svg:
    isPlainText: true
    mediaType: image/svg+xml
enableGitInfo: true
params:
  skipSeconds: false
  useRelativeTime: true
  disableDarkMode: false
  shortDateFormat: 15:04 UTC — Jan 2
  down: "#FF4747"
  systems:
    - name: Gateway
      category: North Coast
    - name: Backup Gateway
      category: North Coast
    - name: Website
      description: The web frontend for the application.
      category: Uncategorized
      link: https://example.com/
    - name: API
      description: The guts of the application.
      category: Uncategorized
    - name: Media Proxy
      description: This is the service responsible for serving images, audio, and
        video. It is reliant on our CDN.
      category: Uncategorized
  dateFormat: January 2, 2006 at 3:04 PM UTC
  brand: "#a029e8"
  enableLastMod: true
  headerTextColor: white
  logo: /img/eviloma.png
  incidentPostsPerPage: 10
  googleAnalytics: UA-00000000-1
  alwaysKeepBrandColor: true
  disableComplexCalculations: false
  useLogo: false
  disrupted: "#FFB800"
  notice: "#6EA6FF"
  incidentHistoryFormat: none
  disableIncidentHistory: false
  ok: "#00D68F"
  categories:
    - name: North Coast
      description: The main servers are located here.
      closed: true
    - name: Empty Category
    - name: Uncategorized
      untitled: true
  description: Eviloma services status
  enableCustomHTML: false
  useLargeHeaderDesign: false
